[package]
name = "pqxdh"
version = "0.1.1"
edition = "2021"

[dependencies]
aes-gcm = "0.9"  
ed25519-compact = "2.1.1"
pqcrypto = "0.17.0"
rand = "0.8.5"
sha3 = "0.9.1"
thiserror = "1.0.37" 
anyhow = "1.0.68"    

#[features]
#default = ["std"]
